version: "3.9"

services:
    php-fpm:
        container_name: php-fpm
        build: ./php-fpm/
        volumes:
            - ./php-fpm/www:/var/www
        restart: always
        # user: "1000:1000"
    nginx:
        container_name: nginx
        build: ./nginx/
        ports:
            - "80:80"
        restart: always
    mysql:
        container_name: mysql
        build: ./mysql/
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: passpass
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: passpass
        volumes:
            - ./mysql/data:/var/lib/mysql
        restart: always
